package com.example.dynamodemo.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import net.minidev.json.JSONObject;

import java.lang.reflect.Field;

@DynamoDBTable(tableName = "payment-order")
public class PaymentOrder {

    private String PK;
    private String originator_account;
    private String creation_date_time;
    private String expiry_date_time;
    private String order_type;
    private String order_status;
    private String instructed_amount;

    public PaymentOrder() {

    }

    public PaymentOrder(String PK, String originator_account, String creation_date_time, String expiry_date_time, String order_type, String order_status, String instructed_amount) {
        this.PK = PK;
        this.originator_account = originator_account;
        this.creation_date_time = creation_date_time;
        this.expiry_date_time = expiry_date_time;
        this.order_type = order_type;
        this.order_status = order_status;
        this.instructed_amount = instructed_amount;
    }

    @DynamoDBHashKey(attributeName = "PK")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return PK;
    }

    @DynamoDBAttribute(attributeName = "originator_account")
    public String getOriginatorAccount() {
        return originator_account;
    }

    @DynamoDBAttribute(attributeName = "creation_date_time")
    public String getCreationDateTime() {
        return creation_date_time;
    }

    @DynamoDBAttribute(attributeName = "expiry_date_time")
    public String getExpiryDateTime() {
        return expiry_date_time;
    }

    @DynamoDBAttribute(attributeName = "order_type")
    public String getOrderType() {
        return order_type;
    }

    @DynamoDBAttribute(attributeName = "order_status")
    public String getStatus() {
        return order_status;
    }

    @DynamoDBAttribute(attributeName = "instructed_amount")
    public String getInstructedAmount() {
        return instructed_amount;
    }

    public void setOriginatorAccount(String originatorAccount) {
        this.originator_account = originatorAccount;
    }

    public void setCreationDateTime(String creationDateTime) {
        this.creation_date_time = creationDateTime;
    }

    public void setExpiryDateTime(String expiryDateTime) {
        this.expiry_date_time = expiryDateTime;
    }

    public void setOrderType(String ordertype) {
        this.order_type = ordertype;
    }

    public void setStatus(String orderStatus) {
        this.order_status = orderStatus;
    }

    public void setId(String id) {
        this.PK = id;
    }
    public void setInstructedAmount(String instructedAmount) {
        this.instructed_amount = instructedAmount;
    }

    public boolean isValidated() {
        return originator_account != null && creation_date_time != null && expiry_date_time != null && order_type != null && order_status != null && instructed_amount != null;
    }

    @Override
    public String toString() {
        JSONObject jsonObject = new JSONObject();
        try {
            for (Field field : getClass().getDeclaredFields()) {
                jsonObject.put(field.getName(), field.get(this));
            }
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return jsonObject.toString();
    }
}



